export const skedliiPlans = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for trying out Skedlii solo",
    badge: "Free Forever",
    badgeColor: "green",
    priceMonthly: 0,
    priceYearly: 0,
    offYearly: 0,
    features: [
      "1 social account",
      "Schedule posts in advance",
      "Basic analytics",
      "AI post suggestions",
      "Mobile access",
    ],
    isPopular: false,
  },
  {
    id: "basic",
    name: "Basic",
    description: "For individuals and small teams getting started",
    badge: "7-day Free Trial",
    badgeColor: "indigo",
    priceMonthly: 5,
    priceYearly: 50,
    offYearly: 16.67,
    priceMonthlyId: "price_1RKwzA4FFNhyBdZ9YVyhyd7a",
    priceYearlyId: "price_1RL2AM4FFNhyBdZ9QX6O2Fq8",
    productId: "prod_SFRsGdub5cP6At",
    features: [
      "5 social accounts",
      "Unlimited scheduled posts",
      "Basic analytics",
      "Single user",
      "AI post suggestions",
      "Mobile access",
    ],
    isPopular: false,
  },
  {
    id: "pro",
    name: "Pro",
    description: "For small teams managing multiple brands",
    badge: "7-day Free Trial",
    badgeColor: "indigo",
    priceMonthly: 25,
    priceYearly: 240,
    offYearly: 20,
    priceMonthlyId: "price_1RL2F54FFNhyBdZ9Xlh9cJbE",
    priceYearlyId: "price_1RL2F54FFNhyBdZ9a0Ed4wjy",
    productId: "prod_SFXJJzqn1ra9MU",
    features: [
      "15 social accounts",
      "Unlimited scheduled posts",
      "Advanced analytics",
      "Create 1 organization",
      "2 team members",
      "Content calendar",
      "Team permissions",
    ],
    isPopular: true,
  },
  {
    id: "business",
    name: "Business",
    description: "For organizations with multiple teams",
    badge: "7-day Free Trial",
    badgeColor: "indigo",
    priceMonthly: 99,
    priceYearly: 950,
    offYearly: 20,
    priceMonthlyId: "price_1RL2Gp4FFNhyBdZ9klw9W7cG",
    priceYearlyId: "price_1RL2Gp4FFNhyBdZ9G7PmThh4",
    productId: "prod_SFXLtiPf6dwGRi",
    features: [
      "Unlimited social accounts",
      "Unlimited scheduled posts",
      "Enterprise analytics & reporting",
      "Unlimited teams & team members",
      "Advanced permissions",
      "Custom integrations",
      "Dedicated account manager",
    ],
    isPopular: false,
  },
];
